### ISSUE TITLE
Chokes on 512x512px image

### ISSUE THREAD

**Issue by salomvary** [kevva/to-ico#13]
If it can't downscale, it should fail with a user friendly exception ("Images larger than 256x256 px are not supported").

```
$ file icon_512x512.png 
icon_512x512.png: PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced

$ node_modules/.bin/to-ico icon_512x512.png 
TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1040:11)
    at Buffer.writeUInt8 (buffer.js:1088:5)
    at createDirectory (node_modules/to-ico/index.js:32:6)
    at Promise.all.then.data (node_modules/to-ico/index.js:98:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)

$ npm list | grep to-ico
└─┬ to-ico-cli@1.0.0
  └─┬ to-ico@1.1.3
```

**Comment by kevva** [comment]
Instead of throwing, we could just resize it to `256x256`, regardless if `resize` is `true` or not.

**Comment by albinekb** [comment]
@kevva if you can tell me which way you'd like it I'd love to send a PR 🙌

**Comment by albinekb** [comment]
maybe @sindresorhus has the magic answer 🦄 😏

**Comment by kevva** [comment]
@albinekb, I think the first step is to just resize the image to `256x256` if it's larger. A PR would be greatly appreciated :+1:.

**Comment by DanielRuf** [comment]
Right.

Also related: https://github.com/kevva/to-ico/issues/20

**Comment by DanielRuf** [comment]
Generally setting the option `{resize: true}` should prevent that.
